### ISSUE TITLE
Support Arduino Micro

### ISSUE THREAD

**Issue by nightflyer88** [Blinkinlabs/PatternPaint#180]
I'm just about to make a support for Arduino Micro. Now I wonder if it under Scene configuration the selection for the controller needs, as I have seen, is recognized anyway automatically?

**Comment by nightflyer88** [comment]
And the FixtureType "Linear" and "Matrix" does not need directly, only the LED width is significant. correct ?

I thought we could make it a little nicer. If the LED width is greater than 1, the FixtureType switches to "Matrix". If you select "Linear", the LED width is reset to 1.

**Comment by cibomahto** [comment]
Great! Actually, the matrix and linear fixture selection is kind of a placeholder- The reason is we also support mapped fixtures (where the LEDs aren't necessarily in a line or a grid), so the user will need to be able to select from at least these three options. The other feature a matrix has (that the linear one doesn't) is the option to select how the rows are wired- some are zigzag type, where every other row starts at the last column and works its way to the front, and others are wired 'straight' where the first LED in each row starts at the first column.

In general it's really best if each issue can be separated- it's easier when the different changes can be pulled in one-by-one, in case there is some issue with some of them.

**Comment by cibomahto** [comment]
Accepted the Arduino Micro portion of this commit here:
https://github.com/Blinkinlabs/PatternPaint/commit/6524cf9761b8f319cb21dc0158b9562bc600deff

**Comment by cibomahto** [comment]
Might be worth considering that there are apparently a bunch of VID/PID pairs that Arduino recognizes as an Arduino Micro:
https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/boards.txt#L341

If that's not an issue for you right now, feel free to close this up and we can create a new issue if anyone finds one of the different boards.
